Create statesync.bash
cosmos/gaia pull request #1027
Opened 2021-10-16 16:50 UTC by faddat

## Description

State sync:

Make gaia happen in about ten minutes

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

2021-10-17 05:01 UTC, zmanian requested changes

2021-10-17 05:01 UTC, zmanian commented on contrib/statesync.bash
> +LATEST_HEIGHT=$(curl -s 162.55.132.230:2011/block | jq -r .result.block.header.height);
Not sure if I'm on board with adding a community IP address but I would feel better about this if was behind dns

2021-10-24 15:29 UTC, faddat commented on contrib/statesync.bash
> +LATEST_HEIGHT=$(curl -s 162.55.132.230:2011/block | jq -r .result.block.header.height);
neither am I :).  

I will rig up a cloudflare thing.

2021-11-16 14:08 UTC, alexanderbez requested changes

2021-11-16 14:08 UTC, alexanderbez commented on contrib/statesync.bash
> +go install ./...
can we use make targets instead please?

2021-11-16 14:08 UTC, alexanderbez commented on contrib/statesync.bash
> +LATEST_HEIGHT=$(curl -s 162.55.132.230:2011/block | jq -r .result.block.header.height);
marking as unresolved until this is updated 👍

2021-11-16 21:13 UTC, faddat commented on contrib/statesync.bash
> +go install ./...
totally

2021-11-16 21:22 UTC, faddat commented
We may or may not want to drop the github action.

2021-11-17 14:26 UTC, alexanderbez approved these changes

2021-11-17 23:03 UTC, zmanian approved these changes

2021-11-17 23:04 UTC, merged