split BREAKING CHANGES into subsections
cosmos/gaia pull request #114
Opened 2019-08-28 23:12 UTC by AdityaSripal

Addresses proposal [here](https://github.com/cosmos/cosmos-sdk/issues/4958#issuecomment-525524517).

Splits BREAKING CHANGES into:

- Client Breaking (breaks cli/REST routes)
- API Breaking (breaks core-sdk function signatures)
- State Machine Breaking

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2019-08-28 23:13 UTC, AdityaSripal commented on CHANGELOG.md
>  * (sdk) Update SDK version to v0.37.0
Not sure where this line is supposed to go. May belong in multiple (if not all) subsections

2019-08-29 15:08 UTC, alexanderbez requested changes
Thanks @AdityaSripal -- left some feedback.

Also, with whatever set of stanzas/sections we agree upon, we should be sure to upgrade them in the header comment:

```
Types of changes (Stanzas):

```

2019-08-29 19:50 UTC, AdityaSripal commented on CHANGELOG.md
> +### API Breaking Changes
Oh i suppose with Gaia there is no API breaking changes. Just copied over from SDK.

I intended for Client to include both CLI and REST route changes. We could split them further if desired tho

2019-08-29 19:57 UTC, alexanderbez commented on CHANGELOG.md
> +### API Breaking Changes
Sure. If that's the case, whats the difference between Client and API? Because I can see ppl getting confused.

2019-08-29 21:34 UTC, AdityaSripal commented on CHANGELOG.md
> +### API Breaking Changes
Explained [here](https://github.com/cosmos/cosmos-sdk/pull/4967#discussion_r319250551)

2019-08-30 15:50 UTC, alexanderbez commented on CHANGELOG.md
> +### Client Breaking Changes
```suggestion
```

2019-08-30 15:50 UTC, alexanderbez commented on CHANGELOG.md
> +
```suggestion
```

2019-08-30 15:50 UTC, alexanderbez approved these changes
ACK

2019-08-30 16:02 UTC, merged