docs: fix blocs typo
cosmos/gaia pull request #1296
Opened 2022-02-24 06:35 UTC by pratikbalar

2022-02-28 17:21 UTC, okwme requested changes

2022-02-28 17:21 UTC, okwme commented on docs/validators/validator-faq.md
> +The [Cosmos Hub](../getting-started/what-is-gaia.md) is based on [Tendermint](https:/blocs/docs.tendermint.com/master/introduction/what-is-tendermint.html) that relies on a set of validators to secur
Is this supposed to be here?

2022-02-28 17:21 UTC, okwme commented on docs/validators/validator-faq.md
> +The [Cosmos Hub](../getting-started/what-is-gaia.md) is based on [Tendermint](https:/blocs/docs.tendermint.com/master/introduction/what-is-tendermint.html) that relies on a set of validators to secur
```suggestion
The [Cosmos Hub](../getting-started/what-is-gaia.md) is based on [Tendermint](https://docs.tendermint.com/master/introduction/what-is-tendermint.html) that relies on a set of validators to secure the network. The role of validators is to run a full node and participate in consensus by broadcasting votes that contain cryptographic signatures signed by the validator's private key. Validators commit new blocks in the blockchain and receive revenue in exchange for their work. Validators must also participate in governance by voting on proposals. Validators are weighted according to their total stake.
```

2022-03-01 10:54 UTC, merged

2022-03-01 13:25 UTC, pratikbalar commented
@okwme Thank you for your fix.