use master branch of cosmos/ledger-cosmos-go
cosmos/gaia pull request #1801
Opened 2022-10-11 04:18 UTC by faddat

While working on Akash today I noticed that there were some **very 
strange** things going on with our ledger imports.  The tl;dr is:

* we should stop maintaining cosmos/ledger-go
* we should ensure that we routinely cut releases of 
cosmos/ledger-go-cosmos

Here's a PR that gets Gaia on the right track, reflecting those changes.

2022-10-13 16:39 UTC, okwme commented
Thanks @faddat .
Zondax maintains both of those repositories.
It was relatively recently that we updated to their latest release (https://github.com/cosmos/gaia/issues/1576, https://github.com/cosmos/gaia/pull/1634).

We need to confirm whether there are API breaking changes that would impact users of gaia to ensure they're included in communications. Have you investigated what are the breaking changes between the updates you've included?
If not, maybe someone from Zondax can help us review this PR—maybe @philipglazman or @jleni?

2022-10-14 13:12 UTC, jleni commented
Hi @faddat @okwme 
As Billy explained, we have recently taken over the maintenance in this org and we are moving to a more predictable release schedule.

Could you provide some more info about these "strange things" you describe? Or it is related only to go.mod issues and a release would clear up the problem?

2022-10-14 15:36 UTC, jleni commented
I have just created this issue https://github.com/cosmos/ledger-cosmos-go/issues/30 to track the repo reorganization that will take place soon

2022-10-24 10:05 UTC, Pantani requested changes

2022-10-24 10:05 UTC, Pantani commented on go.mod
> +	github.com/zondax/ledger-go v0.12.2 // indirect
The `zondax/ledger-go` seems not well maintained. I think we should avoid importing this package into Gaia

2022-11-01 14:13 UTC, okwme commented
thanks for the link to track progress @jleni !
We'll close this PR until the zondax plan for maintained libraries is complete and reference them directly then

2022-11-01 14:13 UTC, closed without merging