fix: gaiad export to stdout, not stderr
cosmos/gaia pull request #2250
Opened 2023-02-24 13:43 UTC by yaruwangway

Please check https://github.com/cosmos/gaia/issues/2249 for issue description. Please test before approval.

2023-02-27 11:50 UTC, yaruwangway commented
Need to decide: which version to include this fix.

2023-03-09 18:59 UTC, mpoke requested changes
Not sure whether we want to fix this in a patch release.

2023-03-09 18:59 UTC, mpoke commented on cmd/gaiad/cmd/root.go
> +
What's the impact of this change on users that already use stderr?

2023-03-16 10:04 UTC, yaruwangway commented on cmd/gaiad/cmd/root.go
> +
if users use `gaiad export > genesis.json 2>&1` before, it will still work.

2023-04-11 14:54 UTC, mpoke commented
Closing due to lack of activity.

2023-04-11 14:54 UTC, closed without merging