update roadmap and release log pages
cosmos/gaia pull request #2275
Opened 2023-03-09 11:04 UTC by MSalopek

This PR updates roadmap and release related pages

2023-03-09 11:24 UTC, mpoke requested changes
See my comments below.

2023-03-09 11:24 UTC, mpoke commented on docs/roadmap/README.md
> +For current roadmap and planned features, check out the Cosmos Hub [Release Log](./cosmos-hub-release-log.md).
Isn't the release log a list of existing features? Why is this part of the roadmap?

2023-03-09 11:24 UTC, mpoke commented on docs/migration/cosmoshub-4-v8-Rho-upgrade.md
> +This document describes the steps for validator and full node operators for the successful execution of the [v8-Rho Upgrade](../roadmap/cosmos-hub-release-log.md#v8-rho-upgrade-completed-march-15-202
Typo. See the date.

2023-03-09 11:24 UTC, mpoke commented on docs/migration/cosmoshub-4-v8-Rho-upgrade.md
> +This document describes the steps for validator and full node operators for the successful execution of the [v8-Rho Upgrade](../roadmap/cosmos-hub-release-log.md#v8-rho-upgrade-completed-march-15-202
Typo. See the date.

2023-03-09 11:24 UTC, mpoke commented on docs/roadmap/cosmos-hub-release-log.md
> +## v8-Rho Upgrade (Completed February 16, 2023)
I would move the date from the tile and add it in bold under the title. Like this, the links to these sections will be simpler.

2023-03-09 11:24 UTC, mpoke commented on README.md
> +To participate in or utilize the current Cosmos Hub testnet, take a look at the [cosmos/testnets](https://github.com/cosmos/testnets) repository. This testnet is for the Lambda Upgrade expected in Q1
Do we want to have a reference to the current version and expected date here? I would like to reduce the number of places we need to update regularly.

2023-03-09 11:27 UTC, MSalopek commented on docs/roadmap/cosmos-hub-release-log.md
> +## v8-Rho Upgrade (Completed February 16, 2023)
Don't think link simplicity matters because they are autogenerated and slugified

2023-03-09 11:30 UTC, MSalopek commented on docs/migration/cosmoshub-4-v8-Rho-upgrade.md
> +This document describes the steps for validator and full node operators for the successful execution of the [v8-Rho Upgrade](../roadmap/cosmos-hub-release-log.md#v8-rho-upgrade-completed-march-15-202
Done

2023-03-09 11:30 UTC, MSalopek commented on docs/migration/cosmoshub-4-v8-Rho-upgrade.md
> +This document describes the steps for validator and full node operators for the successful execution of the [v8-Rho Upgrade](../roadmap/cosmos-hub-release-log.md#v8-rho-upgrade-completed-march-15-202
Duplicated, same as above

2023-03-09 11:38 UTC, MSalopek commented on docs/roadmap/cosmos-hub-release-log.md
> +## v8-Rho Upgrade (Completed February 16, 2023)
Applied the suggestions.

There will be an info box below every title clearly stating the completion date.

Links simplified as suggested

2023-03-09 17:12 UTC, mpoke approved these changes

2023-04-04 10:44 UTC, mmulji-ic commented on docs/roadmap/cosmos-hub-release-log.md
> +# Cosmos Hub Release Log
@jtremback was concerned about breaking links to this document, was this change agreed upon?

2023-04-04 10:45 UTC, mmulji-ic commented on docs/roadmap/README.md
>  ## Cosmos Hub History
I'd move this table to the cosmos-hub-release-log.md file. This readme.md can be the 'planned features doc'.

2023-04-20 18:58 UTC, MSalopek commented
Closing as no longer relevant.
Documentation updates are tracked here: https://github.com/cosmos/gaia/issues/2309

2023-04-20 18:58 UTC, closed without merging