chore: Update changelog for v9.0.2
cosmos/gaia pull request #2335
Opened 2023-03-24 19:28 UTC by glnro

2023-03-25 18:41 UTC, mpoke requested changes

2023-03-25 18:41 UTC, mpoke commented on CHANGELOG.md
> +* (gaia) Replace [tendermint](https://github.com/informalsystems/tendermint) to [comet](https://docs.cometbft.com/v0.34/). See [CHANGELOG.md](https://github.com/cometbft/cometbft/blob/v0.34.27/CHANGE
Let's keep v9.0.2 only with the bump of ICS. We cut afterwards v9.0.3 with the replace to Comet.

2023-03-27 15:31 UTC, mpoke approved these changes

2023-03-27 16:39 UTC, MSalopek approved these changes

2023-03-27 16:40 UTC, merged