Feat : Removed SDK general error types
cosmos/gaia pull request #2496
Opened 2023-05-17 12:02 UTC by ruthishvitwit

## Description

Closes: #2484 

The aim of this PR is to remove usage of SDK general error types in Gaia

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API or client breaking change
* [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry to `CHANGELOG.md`
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

2023-05-17 22:28 UTC, mpoke reviewed
Thanks @ruthishvitwit. Just two nits below.

2023-05-17 22:28 UTC, mpoke commented on x/globalfee/ante/fee.go
> +		return ctx, errorsmod.Wrapf(gaiaerrors.ErrTxDecode, "Tx must implement the sdk.FeeTx interface")
nit: This should not be `Wrapf`

2023-05-17 22:28 UTC, mpoke commented on x/globalfee/ante/fee.go
> +		return ctx, errorsmod.Wrapf(gaiaerrors.ErrInsufficientFee, errMsg)
ditto: `Wrap` instead of `Wrapf`

2023-05-18 04:43 UTC, ruthishvitwit commented on x/globalfee/ante/fee.go
> +		return ctx, errorsmod.Wrapf(gaiaerrors.ErrInsufficientFee, errMsg)
got it sorry my bad

2023-06-13 11:07 UTC, mpoke requested changes
@ruthishvitwit could you please get the CI checks pass?

2023-06-14 07:13 UTC, ruthishvitwit commented
> @ruthishvitwit could you please get the CI checks pass?

@mpoke i have tried to make required changes can u please check for one final time if everything is alright??

2023-06-14 12:32 UTC, MSalopek requested changes
Thanks for your contribution!

Please address the comments.
Importing `gaiaerrors "github.com/cosmos/gaia/v10/types/errors"`
should be replaced with `gaiaerrors "github.com/cosmos/gaia/v11/types/errors"`.

2023-06-14 12:32 UTC, MSalopek commented on ante/ante.go
> +	gaiaerrors "github.com/cosmos/gaia/v10/types/errors"
```suggestion
	gaiaerrors "github.com/cosmos/gaia/v11/types/errors"
```

Please change all occurances. V10 is a previous version, so the tooling will try to pull `gaia/v10` and break the build

2023-06-14 12:32 UTC, MSalopek commented on x/globalfee/ante/fee_utils.go
> +	gaiaerrors "github.com/cosmos/gaia/v10/types/errors"
See above comment.

2023-06-14 12:32 UTC, MSalopek commented on ante/gov_ante.go
> +	gaiaerrors "github.com/cosmos/gaia/v10/types/errors"
See above comment.

2023-06-14 12:35 UTC, ruthishvitwit commented on ante/gov_ante.go
> +	gaiaerrors "github.com/cosmos/gaia/v10/types/errors"
yes thankyou i just figured it out

2023-06-14 13:25 UTC, MSalopek approved these changes
Thanks for addressing the comments!

Approval

2023-06-14 17:05 UTC, mpoke commented
@ruthishvitwit Could you please also resolve the conflicts?

2023-06-16 06:01 UTC, ruthishvitwit commented
@mpoke I have resolved all the conflicts. Can u take a final look into this.?

2023-06-16 07:07 UTC, mpoke commented on go.sum
Did you run `go mod tidy`? Weird that `go.sum` is modified without changes in `go.mod`.

2023-06-16 07:08 UTC, mpoke commented on go.sum
Once this is done, the PR is ready to merge

2023-06-16 07:12 UTC, ruthishvitwit commented on go.sum
sorry about that .. I just did and commited the change

2023-06-16 07:21 UTC, mpoke commented on go.sum
`go.sum` still contains changes.

2023-06-16 08:03 UTC, mpoke approved these changes
Thanks for your contribution @ruthishvitwit.

2023-06-16 08:03 UTC, merged