docs: generate swagger for the new global fee query
cosmos/gaia pull request #2590
Opened 2023-06-14 15:30 UTC by sainoe

## Description

Update the swagger query definition using the refactored Global Fee protos.

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct `docs:` prefix in the PR title
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct `docs:` prefix in the PR title
- [ ] Confirmed all author checklist items have been addressed 
- [ ] Confirmed that this PR only changes documentation
- [ ] Reviewed content for consistency
- [ ] Reviewed content for thoroughness
- [ ] Reviewed content for spelling and grammar
- [ ] Tested instructions (if applicable)

2023-06-14 17:08 UTC, mpoke requested changes

2023-06-14 17:08 UTC, mpoke commented on go.sum
> +github.com/stretchr/testify v1.8.3/go.mod h1:sz/lmYIOXD/1dqDmKjjqLyZ2RngseejIcXlSw2iwfAo=
A docs PR should not update go.sum

2023-06-15 08:13 UTC, mpoke approved these changes

2023-06-30 17:06 UTC, mmulji-ic commented on docs/client/gaia/globalfee/v1beta1/query.swagger.json
> +      "description": "Params defines the set of module parameters."
This should be a bit more descriptive.

2023-06-30 17:07 UTC, mmulji-ic commented on docs/client/gaia/globalfee/v1beta1/query.swagger.json
> +          "description": "max_total_bypass_min_fee_msg_gas_usage defines the total maximum gas usage\nallowed for a transaction containing only messages of types in bypass_min_fee_msg_types\nto bypas
That is a mouthful max_total_bypass_min_fee_msg_gas_usage, did you guys not have other options?

2023-08-09 13:00 UTC, mmulji-ic commented on docs/client/gaia/globalfee/v1beta1/query.swagger.json
> +          "description": "max_total_bypass_min_fee_msg_gas_usage defines the total maximum gas usage\nallowed for a transaction containing only messages of types in bypass_min_fee_msg_types\nto bypas
🆗 this is not changeable now.

2023-08-09 13:03 UTC, mmulji-ic approved these changes

2023-08-09 13:33 UTC, merged