feat: add query local min-gas-price
cosmos/gaia pull request #2627
Opened 2023-06-27 13:34 UTC by yaruwangway

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

2023-06-28 12:57 UTC, mpoke requested changes

2023-06-28 12:57 UTC, mpoke commented on tests/e2e/e2e_rest_regression_test.go
> +	localMinGasPriceQueryPath           = "cosmos/base/node/v1beta1/config"
This is never used.

2023-06-29 08:24 UTC, yaruwangway commented on tests/e2e/e2e_rest_regression_test.go
> +	localMinGasPriceQueryPath           = "cosmos/base/node/v1beta1/config"
I dont understand, what do you mean ?

2023-06-29 09:08 UTC, mpoke commented on tests/e2e/e2e_rest_regression_test.go
> +	localMinGasPriceQueryPath           = "cosmos/base/node/v1beta1/config"
IIUC, this constant is never used in the test.

2023-06-29 09:55 UTC, yaruwangway commented on tests/e2e/e2e_rest_regression_test.go
> +	localMinGasPriceQueryPath           = "cosmos/base/node/v1beta1/config"
you are right, my bad, added test.

2023-06-29 09:56 UTC, yaruwangway commented
@mpoke if PR backport this to v10 ?

2023-06-29 14:18 UTC, mpoke approved these changes

2023-06-30 15:24 UTC, mmulji-ic approved these changes

2023-07-02 20:46 UTC, bitcoinfinancier approved these changes

2023-07-03 09:01 UTC, merged