fix: Removal of liquidity module
cosmos/gaia pull request #2716
Opened 2023-09-06 10:37 UTC by bermuell

## Description

Closes: #2714

Removal of the liquidty staking module as since there is no depency after state removal done in v11

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [ ] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
* [ ] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [ ] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

2023-09-06 12:40 UTC, bermuell commented on app/app.go
> +		upgrade := upgrade
This fixes a linter error ('G601: Implicit memory aliasing in for loop. (gosec)'

2023-09-06 18:58 UTC, mpoke requested changes
Please rebase to main. This changes will go in the next release, i.e., v13.

2023-09-06 18:58 UTC, mpoke commented on go.mod
`go.sum` missing; please run `go mod tidy`

2023-09-07 08:36 UTC, mpoke requested changes

2023-09-07 08:36 UTC, mpoke commented on .changelog/v11.0.0/dependencies/2652-liquidity-removal.md
Move to `.changelog/unreleased/...`.

2023-09-07 08:36 UTC, mpoke commented on .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md
Move to `.changelog/unreleased/...`.

2023-09-07 09:24 UTC, bermuell commented on .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md
Will revert the changes on .changelog/v11.0.0 as PR is targeting 'main' now
Since we're targeting this for 'main' branch, is the removal of v1.6.0-forced-withdrawal to be considered "state braking"?  as there is no state dependency for liquidity anymore and the related state breaking was announced in v11.x release?

2023-09-07 10:03 UTC, mpoke commented on .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md
That makes sense. Since the state was already removed, I don't think it's state breaking.

2023-09-07 10:03 UTC, mpoke approved these changes
Nice work @bermuell.

2023-09-07 15:57 UTC, yaruwangway approved these changes

2023-09-08 11:06 UTC, merged

2023-11-18 05:31 UTC, Frankoxt commented
> <!--
> The production pull request template is for types feat, fix, deps, or refactor.
> -->
> 
> ## Description
> 
> Closes: #2714
> 
> Removal of the liquidty staking module as since there is no depency after state removal done in v11
> 
> ### Author Checklist
> 
> *All items are required. Please add a note to the item if the item is not applicable and
> please add links to any relevant follow up issues.*
> 
> I have...
> 
> * [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
> * [x] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
> * [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
> * [x] Provided a link to the relevant issue or specification
> * [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
> * [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
> * [x] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
> * [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
> * [ ] Updated the relevant documentation or specification
> * [x] Reviewed "Files changed" and left comments if necessary <!-- relevant if the changes are not obvious  -->
> * [x] Confirmed all CI checks have passed
> 
> ### Reviewers Checklist
> 
> *All items are required. Please add a note if the item is not applicable and please add
> your handle next to the items reviewed if you only reviewed selected items.*
> 
> I have...
> 
> * [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
> * [ ] confirmed `!` in the type prefix if API or client breaking change
> * [ ] confirmed all author checklist items have been addressed 
> * [ ] reviewed state machine logic
> * [ ] reviewed API design and naming
> * [ ] reviewed documentation is accurate
> * [ ] reviewed tests and test coverage
>