Assert Proposal 104
cosmos/gaia pull request #2767
Opened 2023-10-19 11:12 UTC by faddat

## Description

It is our determination that the current security policy document on this repository represents a risk to the cosmos hub due to the release of information that can lead to chain halts, eg: "affect consensus participation" by informal systems and amulet, without review of documentation submitted by researchers at notional.

During the process of reporting a complex security issue, both informal systems and amulet have been entirely non-responsive. In total, notional has received three emails pursuant to this issue from amulet.

Because this issue extended over multiple layers of the cosmos stack, we initially chose to involve amulet because their job description with the foundation is security coordination. Unfortunately, that has not been occurring.

It is our opinion that individuals or organizations with security matters to report, who wish to be able to review any findings before publication, likely would not want to work with amulet and informal, due to the fact that amulet published our findings against our express wishes.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct `docs:` prefix in the PR title
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct `docs:` prefix in the PR title
- [ ] Confirmed all author checklist items have been addressed 
- [ ] Confirmed that this PR only changes documentation
- [ ] Reviewed content for consistency
- [ ] Reviewed content for thoroughness
- [ ] Reviewed content for spelling and grammar
- [ ] Tested instructions (if applicable)

2023-10-20 02:03 UTC, faddat commented
Hey guys I just want to let you know that if this does not end up getting merged, I'll take additional steps via governance that ensures that this is no longer the hub official repository.

2023-10-20 09:11 UTC, faddat commented
https://github.com/cometbft/cometbft/pull/1518

2023-10-20 18:29 UTC, faddat commented
https://twitter.com/gadikian/status/1715420667431239731?t=kKTJOnc6OfY6cejRVcJ1wA&s=19

2023-10-21 10:36 UTC, jessica0f0116 commented
Bluntly as a security researcher I think this kind of abusive, bullying behavior will discourage people from disclosing vulnerabilities. It's unkind to maintainers and a misuse of the PR system. faddat seems like someone influential who could make peoples lives difficult (and pretty well-resourced based on the contents of the referenced proposal). So I think I would just avoid any involvement in all of (gestures) this. it's gotten out of hand

2023-10-22 03:46 UTC, faddat commented
Hi, no worries I'm going to show you abusive. But please keep in mind I'm not the one being abusive here's Ethan Buchman

2023-11-17 16:08 UTC, jackzampolin requested changes
We should close this PR in favor of https://github.com/cosmos/gaia/pull/2820

2023-11-17 16:11 UTC, mpoke requested changes
Rejecting in favor of https://github.com/cosmos/gaia/pull/2820

2023-11-17 16:20 UTC, mpoke commented
Closing in favor of https://github.com/cosmos/gaia/pull/2820

2023-11-17 16:20 UTC, closed without merging