chore!: add min commission rates migration (prop 826)
cosmos/gaia pull request #2855
Opened 2023-12-13 15:32 UTC by MSalopek

## Description

Closes: #2768

Add migration for gaia v15 to implement [prop 826](https://www.mintscan.io/cosmos/proposals/826). 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Provided a link to the relevant issue or specification
- [ ] Reviewed "Files changed" and left comments if necessary 
- [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] Confirmed all author checklist items have been addressed
- [ ] Confirmed that this PR does not change production code

2023-12-13 16:20 UTC, mpoke approved these changes
LGTM

2023-12-13 16:20 UTC, mpoke commented on app/upgrades/v15/upgrades.go
> +// adhere to prop 826 which sets the minimum commission rate to 5% for all validators
nit: move comment next to the relevant code

2023-12-13 16:21 UTC, mpoke commented
Get the linter to pass  before merging

2023-12-14 08:44 UTC, p-offtermatt approved these changes
LGTM except for linter. Also, just a reminder to communicate to Hypha to check this when they upgrade the testnet

2023-12-18 14:22 UTC, sainoe commented on app/upgrades/v15/upgrades_test.go
> +
Maybe add a test case setting one validator with MaxRate < MinCommissionRate.

2023-12-18 14:23 UTC, sainoe approved these changes

2023-12-19 10:43 UTC, sainoe commented on app/upgrades/v15/upgrades.go
> +		val := val
Don't think it's required as `val` reference isn't used here.

2024-01-09 10:52 UTC, mpoke requested changes
Add changelog entry.

2024-01-19 09:03 UTC, mpoke approved these changes
LGTM.

2024-01-19 09:03 UTC, mpoke commented on app/upgrades/v15/upgrades.go
> +	params := sk.GetParams(ctx)
Add log messages at the beginning and end of the `UpgradeMinCommissionRate` method, e.g., 
```go
unc UpgradeMinCommissionRate(ctx sdk.Context, sk stakingkeeper.Keeper) {
	ctx.Logger().Info("Migrating min commission rate...")
	// ... 
	ctx.Logger().Info("Finished migrating min commission rate")
```
If it fails, we need to identify fast the bug.

2024-01-19 09:03 UTC, mpoke commented on app/upgrades/v15/upgrades.go
> +// adhere to prop 826 which sets the minimum commission rate to 5% for all validators
This comment is still relevant.

2024-01-19 14:34 UTC, merged