ci: add gov module to interchaintest folder
cosmos/gaia pull request #3408
Opened 2024-11-08 13:40 UTC by dasanchez

## Description

Adds gov module tests to delegator folder:
- Proposal submission
- Proposal deposits
- Proposal vote
- Proposal weighted vote
- Gov module param change
- Messages from gov module account

Successful workflow run:
https://github.com/cosmos/gaia/actions/runs/11732771239

---

### Author Checklist

I have...

- [X] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [X] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Provided a link to the relevant issue or specification
- [ ] Reviewed "Files changed" and left comments if necessary 
- [ ] Confirmed all CI checks have passed

### Reviewers Checklist

I have...

- [ ] Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] Confirmed all author checklist items have been addressed
- [ ] Confirmed that this PR does not change production code

2024-11-13 15:56 UTC, fastfadingviolets requested changes
Ideally we'd like to be able to run the test funcs independently of one another. So the order shouldn't matter that much. I suggest consolidating the ones that all use the same proposal into one function and then removing the number indicator from the other ones. This way there's no global state or anything, and the tests are independent.

2024-11-13 15:56 UTC, fastfadingviolets commented on tests/interchain/delegator/gov_test.go
> +}
all these are the ones that use the proposal you submitted in Test01 right? I'd suggest gathering all of them together into one test func and then using s.Run() to split up the individual stories

2024-11-14 15:39 UTC, dasanchez commented on tests/interchain/delegator/gov_test.go
> +}
Thanks @fastfadingviolets ! I decoupled all tests.

2024-11-14 15:40 UTC, dasanchez commented
Successful workflow run:
https://github.com/cosmos/gaia/actions/runs/11829964071

2024-11-14 15:50 UTC, fastfadingviolets approved these changes

2024-12-09 10:19 UTC, MSalopek approved these changes

2024-12-09 11:41 UTC, merged