ci: new step to check build sanity vs cosmos-sdk master
cosmos/gaia pull request #355
Opened 2020-04-11 19:49 UTC by alessio

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2020-04-12 15:58 UTC, alexanderbez requested changes
Make this an actions job if possible.

2020-04-13 11:52 UTC, alessio commented
@alexanderbez makes sense, will do

2020-04-13 13:54 UTC, alessio commented
@alexanderbez done

2020-04-13 13:55 UTC, marbar3778 commented on .github/workflows/build-latest-sdk.yml
> +      - uses: actions/setup-go@v1
```suggestion
      - uses: actions/setup-go@v2-beta
```

2020-04-13 13:55 UTC, marbar3778 commented on .github/workflows/build-latest-sdk.yml
> +        shell: bash
```suggestion
```

making these updates in the sdk as well. just found it

2020-04-13 13:56 UTC, tac0turtle approved these changes
LGTM

2020-04-13 14:40 UTC, alexanderbez commented
Looks good but the job is failing.

2020-04-13 14:40 UTC, alexanderbez approved these changes
Looks good but the job is failing.

2020-04-13 14:42 UTC, alessio commented
@alexanderbez yeah it's failing cause we're waiting on https://github.com/cosmos/gaia/pull/288. No harm is done if we merge this in the meantime.

2020-04-13 14:50 UTC, alexanderbez commented
Got it, then I leave it to you to merge when ready.

2020-04-17 21:01 UTC, jackzampolin commented
This is great improvement

2020-04-20 12:39 UTC, jgimeno approved these changes

2020-05-20 13:36 UTC, marbar3778 commented
what is the benefit of having gaia build against master of the sdk?

before it was due to not having gaiad & gaiacli but now the sdk has simd and simcli

2020-05-20 13:58 UTC, alessio commented
> what is the benefit of having gaia build against master of the sdk?

To ensure that `gaia`'s master always builds against `cosmos-sdk`'s latest master branch

2020-05-20 14:23 UTC, marbar3778 commented
and what is the benefit for gaia to always be up to date with master?

just for context when a external module gets added to Gaia this will be possible unless that module also keeps up with master

2020-05-20 14:44 UTC, alessio commented
> this will not be possible unless that module also keeps up with master

This is not meant to become a blocking job for a PR to be merged. It just gives the PR author additional information re: whether their PR builds successfully against cosmos-sdk master

2020-05-28 11:35 UTC, marbar3778 commented
should we just merge this and see what people think about it?

2020-05-28 13:13 UTC, merged