Add migrate command to gaiad
cosmos/gaia pull request #60
Opened 2019-06-28 15:02 UTC by sabau

- need to update the hash once https://github.com/cosmos/cosmos-sdk/pull/4471 in cosmos sdk is merged

Signed-off-by: Karoly Albert Szabo <szabo.karoly.a@gmail.com>

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry: `clog add [section] [stanza] [message]`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2019-06-28 16:48 UTC, alexanderbez requested changes
Doesn't this need the new SDK version in `go.mod`?

2019-07-01 10:11 UTC, sabau commented
Yeah I was waiting for the Migrate command to be merged before updating the `go.sum` here

2019-07-04 21:14 UTC, sabau commented
https://github.com/cosmos/gaia/pull/56 should land first, fixes all the problems in this branch

2019-07-05 13:50 UTC, alexanderbez approved these changes
ACK

2019-07-05 13:55 UTC, merged

2019-07-05 13:57 UTC, alessio requested changes
There's a minor and weird thing that might be worth of extra investigation

2019-07-05 13:57 UTC, alessio commented on go.mod
> +	github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c // indirect
This seems a sort of downgrade. I'd like to investigate further before approving this