chore: update tendermint
cosmos/gaia pull request #964
Opened 2021-09-10 14:36 UTC by okwme

Closes: #XXX

## Description

Adds the Tendermint release https://github.com/tendermint/tendermint/releases/tag/v0.34.13

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/main/README.md#merging-a-pr))

2021-09-11 01:41 UTC, faddat approved these changes
this is the way

2021-09-11 01:43 UTC, faddat requested changes
https://github.com/cosmos/gaia/blob/db6c6feef8463ee79e71b2db289fe0f3e2e8f630/go.mod#L20

you need to update the replace line, too, or tendermint does not actually update.

2021-09-16 09:34 UTC, yaruwangway approved these changes

2021-09-16 09:34 UTC, merged

2021-09-16 09:37 UTC, marbar3778 commented
this is dependant on some sdk/iavl updates. they should land shortly