Add router module to Vega upgrade
cosmos/gaia pull request #983
Opened 2021-09-21 23:41 UTC by jackzampolin

2021-09-22 12:23 UTC, yaruwangway reviewed
Hi Jack, it is great that we can include router module to gaia vega-rc2 release!
Please confirm if the following code change need to be added:
- add `routertypes.ModuleName` in `app.mm.SetOrderBeginBlockers` and `app.mm.SetOrderInitGenesis`
-  add `fromVM[routertypes.ModuleName] = 0` if the router module do not want to skip init genesis. like this:https://github.com/cosmos/gaia/blob/06d6f8f29d989da7a5275e2a664d7ca7bf1992d8/app/app.go#L565
- add the router module store in the store upgrade. like here: https://github.com/cosmos/gaia/blob/06d6f8f29d989da7a5275e2a664d7ca7bf1992d8/app/app.go#L579

2021-09-22 12:23 UTC, yaruwangway commented on app/app.go
> +	router "github.com/strangelove-ventures/packet-forward-middleware/router"
no need to write "router" if the alias is the same name as the package

2021-09-22 13:34 UTC, alexanderbez requested changes
This needs to go into `main` then backported into the release branch. Otherwise, LGTM.

2021-09-22 21:14 UTC, jackzampolin commented
Ok so this is good, but I just want to make sure to test the e2e with this build. Should have this done by eow

2021-09-22 21:14 UTC, jackzampolin commented
Will rebase against `main`

2021-10-13 18:51 UTC, okwme commented
this work was cherry-picked by @yaruwangway and added to the `vega-rc2` branch as part of https://github.com/cosmos/gaia/pull/979. Going to close this PR unless there's another reason to keep it open.

2021-10-13 18:51 UTC, closed without merging